apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-dnsmasq
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/pihole/etc-dnsmasq