apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaazingchatwebapplication-myweb
  namespace: myweb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: C:\\k8s\\volumes\\windows\\KaazingChatWebApplication
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - windows

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pushnotificationwebap-myweb
  namespace: myweb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path:  C:\\k8s\\volumes\\windows\\PushNotificationWebAp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - windows

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: taipeistarbankmessageclientwebapi-myweb
  namespace: myweb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: C:\\k8s\\volumes\\windows\\TaipeiStarBankMessageClientWebApi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - windows
