apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb-gatewaypod
  name: myweb-gatewaypod-deployment
  namespace: myweb
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb-gatewaypod
  template:
    metadata:
      labels:
        app: myweb-gatewaypod
    spec:
      containers:
        - name: socat
          image: alpine/socat
          command: ["/bin/sh", "-c"]
          args:
            - |
              socat TCP-LISTEN:80,fork,reuseaddr TCP:myweb-internal-service.myweb.svc.cluster.local:80 &
              socat TCP-LISTEN:1443,fork,reuseaddr TCP:myweb-internal-service.myweb.svc.cluster.local:1443 &
              socat TCP-LISTEN:8172,fork,reuseaddr TCP:myweb-internal-service.myweb.svc.cluster.local:8172 &
              tail -f /dev/null
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 1443
              protocol: TCP
            - containerPort: 8172
              protocol: TCP