apiVersion: v1
kind: Pod
metadata:
  name: webserver-a
  labels:
    app: webserver-a
spec:
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: win-node1
  containers:
  - name: web
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022
    ports:
    - containerPort: 80
    command:
      - powershell
      - -Command
      - |
        Start-Service W3SVC; while ($true) { Start-Sleep -Seconds 3600 }
  restartPolicy: Never
