apiVersion: v1
kind: Pod
metadata:
  name: curl-b
  labels:
    app: curl-b
spec:
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: win-node2
  containers:
  - name: curl
    image: mcr.microsoft.com/powershell:lts-nanoserver-ltsc2022
    command:
      - pwsh
      - -Command
      - |
        Start-Sleep -Seconds 15;
        $target = (Get-Content env:POD_A_IP);
        Write-Host "Testing connection to $target ...";
        Invoke-WebRequest -Uri "http://$target" -UseBasicParsing;
        Start-Sleep -Seconds 3600
    env:
    - name: POD_A_IP
      value: "10.1.93.160"
  restartPolicy: Never
