apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: windows-pool
spec:
  cidr: 192.168.100.0/24
  nodeSelector: "kubernetes.io/os == 'windows'"
  ipipMode: Never
  vxlanMode: Never
  natOutgoing: true
  disabled: false
  strictAffinity: true