apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kaazingwebsocket-gatewaypod
  name: kaazingwebsocket-gatewaypod-deployment
  namespace: kaazingwebsocket
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaazingwebsocket-gatewaypod
  template:
    metadata:
      labels:
        app: kaazingwebsocket-gatewaypod
    spec:
      containers:
        - name: socat
          image: alpine/socat
          command: ["/bin/sh", "-c"]
          args:
            - |
              socat TCP-LISTEN:8001,fork,reuseaddr TCP:kaazingwebsocket-internal-service.kaazingwebsocket.svc.cluster.local:8001 &
              socat TCP-LISTEN:9001,fork,reuseaddr TCP:kaazingwebsocket-internal-service.kaazingwebsocket.svc.cluster.local:9001 &
              tail -f /dev/null
          ports:
            - containerPort: 8001
              protocol: TCP
            - containerPort: 9001
              protocol: TCP