apiVersion: v1
kind: PersistentVolume
metadata:
  name: tibcoems-config
  namespace: tibcoems
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/tibcoems/config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tibcoems-certs
  namespace: tibcoems
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/tibcoems/certs