apiVersion: v1
kind: Service
metadata:
  labels:
    svc: tibcoems-external-service
  name: tibcoems-external-service
  namespace: tibcoems
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.134.207
  ports:
    - name: "7222"
      port: 7222
      targetPort: 7222
    - name: "7243"
      port: 7243
      targetPort: 7243
  selector:
    app: tibcoems-gatewaypod
