apiVersion: v1
kind: Service
metadata:
  labels:
    svc: tibcoems-internal-service
  name: tibcoems-internal-service
  namespace: tibcoems
spec:
  type: ClusterIP
  ports:
    - name: tibcoems-tcp
      port: 7222
      protocol: TCP
      targetPort: 7222
    - name: tibcoems-ssl
      port: 7243
      protocol: TCP
      targetPort: 7243
  selector:
     app: tibcoems
  sessionAffinity: None