apiVersion: v1
kind: Service
metadata:
  name: npm-proxy
  namespace: npm
  annotations:
    metallb.universe.tf/allow-shared-ip: npm-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.134.204
  type: LoadBalancer
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 80
  - name: proxy-ssl
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: npm

---

apiVersion: v1
kind: Service
metadata:
  name: npm-admin-ui
  namespace: npm
  annotations:
    metallb.universe.tf/allow-shared-ip: npm-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.134.204
  type: LoadBalancer
  ports:
  - name: admin-ui
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: npm
