apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
    linkerd.io/inject: enabled
  labels:
    app: sqlserver
  name: sqlserver-deployment
  namespace: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe --file docker-compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        app: sqlserver
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: 1qaz!QAZ
          image: mcr.microsoft.com/mssql/server:2022-latest
          name: sql-server
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/opt/mssql/data
            - name: log
              mountPath: /var/opt/mssql/log
            - name: secrets
              mountPath: /var/opt/mssql/secrets
            - name: backup
              mountPath: /var/opt/mssql/backup
          #command:
            #- sleep
            #- "3600000"
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /shared/volumes/mssql/data
        - name: log
          hostPath:
            path: /shared/volumes/mssql/log
        - name: secrets
          hostPath:
            path: /shared/volumes/mssql/secrets
        - name: backup
          hostPath:
            path: /shared/volumes/mssql/backup
