apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
  namespace: sqlserver
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/mssql/data