apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
  volumeName: mssql-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-log
  namespace: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
  volumeName: mssql-log

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-secrets
  namespace: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: microk8s-hostpath
  volumeName: mssql-secrets

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-backup
  namespace: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
  volumeName: mssql-backup