apiVersion: v1
kind: Service
metadata:
  labels:
    svc: sqlserver-external-service
  name: sqlserver-external-service
  namespace: sqlserver
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.134.201
  ports:
    - name: "2433"
      port: 2433
      targetPort: 2433
  selector:
    app: sqlserver-gatewaypod