apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: myweb
  name: myweb-service
  namespace: myweb
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.134.211
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "1443"
      port: 1443
      targetPort: 1443
    - name: "8172"
      port: 8172
      targetPort: 8172
      protocol: TCP
  selector:
    io.kompose.service: myweb