apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: sqlserver
  name: sqlserver
  namespace: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe --file docker-compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: sqlserver
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - env:
             - name: ACCEPT_EULA
               value: "Y"
             - name: MSSQL_ENABLE_HADR
               value: "1"
             - name: MSSQL_AGENT_ENABLED
               value: "1"
             - name: MSSQL_SA_PASSWORD
               value: 1qaz!QAZ
          image: mcr.microsoft.com/mssql/server:2022-latest
          name: sql-server
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/opt/mssql/data
            - name: log
              mountPath: /var/opt/mssql/log
            - name: secrets
              mountPath: /var/opt/mssql/secrets
            - name: backup
              mountPath: /var/opt/mssql/backup
          #command:
            #- sleep
            #- "3600000"
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sqlserver-pvc
        - name: log
          hostPath:
            path: /shared/volumes/mssql/log
        - name: secrets
          hostPath:
            path: /shared/volumes/mssql/secrets
        - name: backup
          hostPath:
            path: /shared/volumes/mssql/backup
