apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-pihole
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/Volumes/pihole/etc-pihole