apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaazing-read-pods-global
subjects:
- kind: ServiceAccount
  name: default
  namespace: kaazingwebsocket
roleRef:
  kind: ClusterRole
  name: pod-reader-global
  apiGroup: rbac.authorization.k8s.io