apiVersion: v1
kind: Service
metadata:
  labels:
    svc: myweb-internal-service
  name: myweb-internal-service
  namespace: myweb
spec:
  type: ClusterIP
  ports:
    - name: myweb-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: myweb-ssl
      port: 1443
      protocol: TCP
      targetPort: 1443
    - name: myweb-iisremote
      port: 8172
      protocol: TCP
      targetPort: 8172
  selector:
     app: myweb
  sessionAffinity: None