apiVersion: v1
kind: Service
metadata:
  labels:
    svc: myweb-external-service
  name: myweb-external-service
  namespace: myweb
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.134.211
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "1443"
      port: 1443
      targetPort: 1443
    - name: "8172"
      port: 8172
      targetPort: 8172
      protocol: TCP
  selector:
    app: myweb-gatewaypod