apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: asuscomm
  labels:
    app: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: docker.io/pihole/pihole:2025.02.6
        imagePullPolicy: Never
        ports:
        - containerPort: 80