apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  namespace: nginx-proxy-manager
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.134.202
  type: LoadBalancer
  selector:
    app: nginx-proxy-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: admin
      port: 81
      targetPort: 81
      nodePort: 30081
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443