apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file D:\Docker\Nginx Proxy Manager\docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nginx-proxy-manager
  name: nginx-proxy-manager
  namespace: npm-ori
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-proxy-manager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file D:\Docker\Nginx Proxy Manager\docker-compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: nginx-proxy-manager
    spec:
      containers:
        - image: jc21/nginx-proxy-manager:latest
          imagePullPolicy: Always
          name: nginx-proxy-manager
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 81
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 853
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: letsencrypt
              mountPath: /etc/letsencrypt
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /shared/volumes/nginx-proxy-manager/data
        - name: letsencrypt
          hostPath:
            path: /shared/volumes/nginx-proxy-manager/letsencrypt
