apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: tibcoems
  name: tibcoems-service
  namespace: tibcoems
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.134.207
  type: LoadBalancer
  ports:
    - name: "7222"
      port: 7222
      targetPort: 7222
    - name: "7243"
      port: 7243
      targetPort: 7243
  selector:
    io.kompose.service: tibcoems
