apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
    linkerd.io/inject: enabled
  labels:
    io.kompose.service: tibcoems
  name: tibcoems-deployment
  namespace: tibcoems
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tibcoems
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe --file docker-compose.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: tibcoems
    spec:
      volumes:
        - name: tibcoems-config
          persistentVolumeClaim:
            claimName: tibcoems-config
        - name: tibcoems-certs
          persistentVolumeClaim:
            claimName: tibcoems-certs
      containers:
        - env:
            - name: TZ
              value: Asia/Taipei
          image: tibco:8.5.1
          imagePullPolicy: Never
          name: tibcoems
          command: ["/opt/tibco/ems/8.5/bin/tibemsd"]
          args: ["-config", "/opt/tibco/ems/config/tibemsd.conf"]
          ports:
            - containerPort: 7222
              protocol: TCP
            - containerPort: 7243
              protocol: TCP
          volumeMounts:
            - name: tibcoems-config
              mountPath: "/opt/tibco/ems/config"
            - name: tibcoems-certs
              mountPath: "/etc/secret"
      #hostname: leonpc.asuscomm.com
      restartPolicy: Always
