apiVersion: v1
kind: Service
metadata: 
  labels:
    svc: kaazingwebsocket-external-service
  name: kaazingwebsocket-external-service
  namespace: kaazingwebsocket
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.134.208
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    app: kaazingwebsocket-gatewaypod
