apiVersion: v1
kind: Service
metadata:
  name: iis-service
  namespace: iis
spec:
  selector:
    app: iis
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.134.212
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80