apiVersion: v1
kind: PersistentVolume
metadata:
  name: npm-data
  namespace: npm
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/npm/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: npm-letsencrypt
  namespace: npm
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/npm/letsencrypt