apiVersion: v1
kind: PersistentVolume
metadata:
  name: npm-pv-data
  namespace: npm
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /var/snap/microk8s/common/default-storage/npm/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: npm-pv-letsencrypt
  namespace: npm
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /var/snap/microk8s/common/default-storage/npm/letsencrypt
