apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-data
  namespace: npm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: microk8s-hostpath
  volumeName: npm-pv-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-letsencrypt
  namespace: npm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: microk8s-hostpath
  volumeName: npm-pv-letsencrypt
