apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe --file D:\KaazingChatWebApplication_DockerCompose\linux\Kaazing Websocket_cluster1\docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: kaazing-gateway
  name: kaazing-gateway
  namespace: kaazing-gateway
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.134.208
  type: LoadBalancer
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: kaazing-gateway
