apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaazing-config
  namespace: kaazing-gateway
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/kaazing/config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaazing-log
  namespace: kaazing-gateway
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/kaazing/log

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaazing-certs
  namespace: kaazing-gateway
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/kaazing/certs