apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-pihole
  namespace: pihole
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-pihole
  template:
    metadata:
      labels:
        app: gateway-pihole
    spec:
      containers:
        - name: socat
          image: alpine/socat
          command: ["/bin/sh", "-c"]
          args:
            - |
              socat TCP-LISTEN:80,fork,reuseaddr TCP:svc-internal-pihole-tcp.pihole.svc.cluster.local:80 &
              socat TCP-LISTEN:443,fork,reuseaddr TCP:svc-internal-pihole-tcp.pihole.svc.cluster.local:443 &
              socat TCP-LISTEN:53,fork,reuseaddr TCP:svc-internal-pihole-tcp.pihole.svc.cluster.local:53 &
              socat UDP-LISTEN:53,fork,reuseaddr UDP:svc-internal-pihole-udp.pihole.svc.cluster.local:53 &
              socat UDP-LISTEN:67,fork,reuseaddr UDP:svc-internal-pihole-udp.pihole.svc.cluster.local:67 &
              tail -f /dev/null
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 67
              protocol: UDP