apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: pihole
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: microk8s-hostpath
  hostPath:
    path: /shared/volumes/pihole/etc/pihole1