apiVersion: v1
kind: Service
metadata:
  annotations:
    #metallb.universe.tf/address-pool: network-services
    metallb.universe.tf/allow-shared-ip: pihole-svc
  name: svc-external-pihole-udp
  namespace: pihole
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.134.205
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: client-udp
      port: 67
      protocol: UDP
      targetPort: 67
  selector:
    app: gateway-pihole
  sessionAffinity: None