syncer:
  extraArgs:
  - --tls-san=192.168.134.220,vcluster.asuscomm.com
sync:
  nodes:
    enabled: true
  persistentvolumes:
    enabled: true
  persistentvolumeclaims:
    enabled: true
  configmaps:
    enabled: true
  secrets:
    enabled: true
  endpoints:
    enabled: true
  services:
    enabled: true