apiVersion: v1
kind: Service
metadata:
  name: vcluster-leon0816-service
  namespace: leon0816
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer # or NodePort
  loadBalancerIP: 192.168.134.230
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: vcluster