apiVersion: v1
kind: Service
metadata:
  name: svc-internal-pihole-udp
  namespace: pihole
spec:
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: client-udp
      port: 67
      protocol: UDP
      targetPort: 67
  selector:
    app: pihole
  sessionAffinity: None
  type: ClusterIP