apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: sqlserver
  name: sqlserver-compose
  namespace: sqlserver
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.134.201
  ports:
    - name: "2433"
      port: 2433
      targetPort: 1433
  selector:
    io.kompose.service: sqlserver
