apiVersion: v1
kind: Service
metadata:
  labels:
    app: mssql-service
  name: sqlserver
  namespace: sqlserver
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.134.202
  ports:
    - name: "2433"
      port: 2433
      targetPort: 1433
  selector:
    app: mssql
