apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: sqlserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  #storageClassName: microk8s-hostpath
  volumeName: sqlserver-pv