version: '3.0'
services:
  kaazingchatapi:
    build:
      context: ./KaazingChatApi_iis
      dockerfile: Dockerfile
    image: kaazingchatapi
    container_name: kaazingchatapi
    platform: windows
    isolation: hyperv
    environment:
      - TZ=Asia/Taipei
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
