apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaazingchatapi-website
  namespace: kaazingchatapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: microk8s-hostpath
  volumeName: kaazingchatapi-website

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaazingchatapi-videostream
  namespace: kaazingchatapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
  volumeName: kaazingchatapi-videostream

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaazingchatapi-faillog
  namespace: kaazingchatapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: microk8s-hostpath
  volumeName: kaazingchatapi-faillog

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaazingchatapi-iislog
  namespace: kaazingchatapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: microk8s-hostpath
  volumeName: kaazingchatapi-iislog

