apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: kaazingchatapi
  name: kaazingchatapi-service
  namespace: kaazingchatapi
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.134.210
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "8172"
      port: 8172
      targetPort: 8172
      protocol: TCP
  selector:
    io.kompose.service: kaazingchatapi
