apiVersion: v1
kind: Service
metadata:
  labels:
    svc: kaazingchatapi-internal-service
  name: kaazingchatapi-internal-service
  namespace: kaazingchatapi
spec:
  type: ClusterIP
  ports:
    - name: kaazingchatapi-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: kaazingchatapi-ssl
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: kaazingchatapi-iisremote
      port: 8172
      protocol: TCP
      targetPort: 8172
  selector:
     app: kaazingchatapi
  sessionAffinity: None