apiVersion: v1
kind: Service
metadata:
  labels:
    svc: kaazingchatapi-external-service
  name: kaazingchatapi-external-service
  namespace: kaazingchatapi
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.134.210
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "8172"
      port: 8172
      targetPort: 8172
      protocol: TCP
  selector:
    app: kaazingchatapi-gatewaypod
